services:
  build-lambda-zip-auth_register:
    build: "deployUtils/BuildLambdaDeployment/"
    volumes:
      - ./backend/authRegister:/usr/src/lambda
  build-lambda-zip-auth-login:
    build: "deployUtils/BuildLambdaDeployment/"
    volumes:
      - ./backend/authLogin:/usr/src/lambda
  build-lambda-zip-actions-get-items:
    build: "deployUtils/BuildLambdaDeployment/"
    volumes:
      - ./backend/actionsGetItems:/usr/src/lambda
  build-lambda-zip-actions-add-item:
    build: "deployUtils/BuildLambdaDeployment/"
    volumes:
      - ./backend/actionsAddItem:/usr/src/lambda
  build-lambda-zip-actions-delete-item:
    build: "deployUtils/BuildLambdaDeployment/"
    volumes:
      - ./backend/actionsDeleteItem:/usr/src/lambda
